class CreateKeywords < ActiveRecord::Migration[5.2]
  def change
    create_table :keywords do |t|
      t.string :name, index: true
      t.timestamps
    end
    
    ['1800s', '1920s', '1930s', '1940s', '1950s', '1960s', '1970s', '3d', 'adobe', 'aerial', 'agate', 'aged', 
     'air balloon', 'airplane', 'alien', 'alligator', 'alocasia', 'alpine', 'aluminum', 'america', 'anchor',
     'angel', 'animal', 'animal print', 'animal skin', 'animation', 'ant', 'antique', 'apple', 'aqua', 'aquarium',
     'aquatic', 'arches', 'architectural', 'architecture', 'arctic', 'argyle', 'arrow', 'arrowroot', 'art',
     'artichoke', 'artistic', 'asia', 'asian', 'aspen', 'astronomy', 'atlantic', 'automobile', 'autumn',
     'baby animals', 'ballerina', 'ballet', 'balloon', 'balls', 'bamboo', 'bamboo lattice', 'banana',
     'banana leaf', 'bark', 'barn', 'baroque', 'baseball', 'basket', 'basketball', 'basketweave', 'bath', 'batik',
     'beach', 'bears', 'bee', 'beetle', 'bell', 'berry', 'bike', 'bird', 'bird of paradise', 'birdcage', 'birdhouse',
     'block print', 'blonde', 'blossom', 'blueprint', 'blur', 'boat', 'bohemian', 'boho', 'bold', 'book', 'bookcase',
     'bookshelf', 'botanical', 'bouquet', 'bow', 'box', 'braid', 'branch', 'brass', 'brick', 'bridge', 'british',
     'broadway', 'brocade', 'brooklyn', 'brush', 'brushed', 'brushstrokes', 'bubble', 'bud', 'bug', 'building',
     'bunny', 'burgundy', 'burlap', 'bus', 'butterfly', 'button', 'cabin', 'cable knit', 'cactus', 'cage',
     'california', 'camel', 'campfire', 'candy stripe', 'capiz', 'car', 'cards', 'carpet', 'carriage', 'carrot',
     'cartography', 'cartoon', 'carved', 'castle', 'cat', 'cathedral', 'cattail', 'celtic knot', 'cement', 'ceramic',
     'chain link', 'chair', 'chalk', 'chalkboard', 'charming', 'check', 'cheetah', 'chenille', 'cherry',
     'cherry blossom', 'cherub', 'chess', 'chevron', 'chicken', 'child', 'chinese', 'chinoiserie', 'chrysanthemums',
     'church', 'cinderblock', 'circle', 'circus', 'city', 'cityscape', 'classic', 'classical', 'clay', 'clean',
     'clock', 'cloud', 'clover', 'clown', 'coffee', 'collage', 'colored glass', 'colorful', 'column', 'comic book',
     'concrete', 'confetti', 'contour', 'conversational', 'coral', 'coral reef', 'cork', 'corrugated', 'country',
     'countryside', 'courtship', 'cow', 'cowboy', 'cowhide', 'crab', 'cracked', 'crackle', 'cracks', 'crane',
     'craquelure', 'crate', 'creature', 'crinkle', 'criss cross', 'cross stitch', 'crosshatch', 'crystal', 'cube',
     'cupid', 'curl', 'cursive', 'curtain', 'cushion', 'cute', 'dainty', 'daisy', 'dance', 'day of the dead',
     'decorative', 'deer', 'delicate', 'desert', 'detailed', 'dia de los muertos', 'diagonal', 'diamond', 'dice',
     'dimension', 'dimensional', 'disco', 'disney', 'distressed', 'ditsy', 'dog', 'doily', 'doll', 'dolphin',
     'donkey', 'dot', 'dotted', 'dotted line', 'dramatic', 'drawing', 'dreamy', 'duck', 'dyed', 'eagle', 'earth',
     'earthen', 'eclectic', 'eiffle tower', 'elegant', 'elephant', 'embellishent', 'embossed', 'embroidery',
     'england', 'etched', 'ethereal', 'european', 'exposed brick', 'expressionism', 'expressionistic', 'fabric',
     'fabric texture', 'faded', 'fancy', 'fans', 'fantasy', 'farm', 'fashion', 'faux', 'faux effects',
     'faux grasscloth', 'faux leather', 'faux marble', 'faux surface', 'faux wood', 'feather', 'feminine', 'fern',
     'fiber', 'field', 'fifties', 'figure skating', 'figures', 'filigree', 'finch', 'fine line', 'firewood', 'fish',
     'fishing', 'flag', 'flagstone', 'flamingo', 'flannel', 'fleur', 'fleur de lis', 'flock', 'floorboard', 'flooring',
     'floral', 'flourish', 'flower', 'fog', 'foil', 'foliage', 'folk', 'folk art', 'food', 'football', 'forest',
     'formal', 'forties', 'fox', 'foxhunt', 'fractal', 'fracture', 'fragment', 'frames', 'french', 'fresco', 'frieze',
     'frog', 'frond', 'frost', 'fruit', 'fun', 'funny', 'galaxy', 'gallery wall', 'game', 'garden', 'Gatsby', 'gazebo',
     'geese', 'gem', 'gemstone', 'geode', 'geography', 'gesso', 'gillter', 'gingham', 'giraffe', 'girl', 'girly',
     'glam', 'glamourous', 'glitter', 'glitz', 'glossy', 'goat', 'golf', 'goose', 'gradient', 'grand', 'granite',
     'grape', 'graphic', 'grass', 'graze', 'grecian', 'greenery', 'grid', 'griffin', 'gritty', 'groovy', 'grunge',
     'halftone', 'hammered', 'handcrafted', 'handmade', 'hankercheif', 'harlequin', 'harp', 'harvest', 'hat', 'hawaii',
     'hawaiian shirt', 'heart', 'hedge', 'heirlooms', 'hello kitty', 'henna', 'herbs', 'heritage', 'herringbone',
     'hexagon', 'hibiscus', 'hide', 'hieroglyphs', 'hill', 'himalayas', 'hippie', 'historical', 'hockey', 'hologram',
     'holographic', 'home', 'honeycomb', 'horizontal stripe', 'horse', 'houndstooth', 'house', 'hummingbird',
     'hunting', 'hyacinth', 'hydrangea', 'ice', 'ice skating', 'ikat', 'illusion', 'indigo', 'industrial', 'ink',
     'inkblot', 'inlay', 'insect', 'intricate', 'iris', 'ironwork', 'island', 'ivy', 'jacobean', 'japanese',
     'jellyfish', 'jewelry', 'jockey', 'joshua tree', 'jungle', 'jute', 'kaleidoscope', 'kangaroo', 'kettle',
     'key', 'kid', 'kingdom', 'kitchen', 'kitschy', 'kitten', 'knit', 'knot', 'koala', 'koi', 'lace', 'lacy',
     'lady bug', 'lake', 'lamb', 'landscape', 'large stripe', 'lasso', 'latin', 'lattice', 'laurel', 'leaf',
     'leather', 'leaves', 'lemon', 'leopard', 'leopard print', 'library', 'lily', 'lily pad', 'limestone',
     'line drawing', 'linear', 'linen', 'link', 'linocut', 'lion', 'lobster', 'lodge', 'logs', 'lotus', 'love',
     'luggage', 'lunar', 'lush', 'luxe', 'luxurious', 'macro', 'magical', 'mailbox', 'majestic', 'malachite',
     'mansion', 'manhattan', 'map', 'marble', 'marijuana', 'masculine', 'matte', 'mauve', 'maze', 'medallion',
     'metal', 'metal leaf', 'mica', 'microscopic', 'mid-century', 'mid-century modern', 'mineral', 'minimal',
     'minimalist', 'mirror', 'mixed pattern', 'mixed stripe', 'mod', 'modern', 'molding', 'monkey', 'monochrome',
     'monster', 'moon', 'mosaic', 'mother of pearl', 'motif', 'mottled', 'mountain', 'mug', 'mushroom', 'music',
     'musical notes', 'mylar', 'mythical', 'nature', 'nautical', 'needle point', 'neon', 'net', 'new york',
     'newspaper', 'night', 'nostalgia', 'novelty', 'nyc', 'ocean', 'oceanic', 'ogee', 'olive', 'ombre', 'onion',
     'opal', 'opalescent', 'optic', 'optical', 'opulent', 'orante', 'orchard', 'ornament', 'ornamental', 'ornate',
     'ostrich', 'outdoor', 'outerspace', 'oval', 'overlay', 'owl', 'oxidized', 'pacific', 'paddleboat', 'paintable',
     'paisley', 'pajamas', 'palette', 'palm', 'pansy', 'paper', 'parasol', 'paris', 'parrot', 'pastel', 'pastoral',
     'patina', 'peace sign', 'peach', 'peacock', 'peak', 'pearl', 'pearlescent', 'peony', 'people', 'petal',
     'photograph', 'picnic', 'pig', 'pine cone', 'pine needles', 'pine tree', 'pinstripe', 'pirate', 'planes',
     'planet', 'plank', 'plant', 'plaster', 'playful', 'playing cards', 'plume', 'pointillism', 'poker', 'polished',
     'polka dot', 'pond', 'poodle', 'pool', 'poppy', 'postage', 'pottery', 'preppy', 'princess', 'prism',
     'privacy film', 'psychedelic', 'puppies', 'quaint', 'quilt', 'quilted', 'quirky', 'rabbit', 'raccoon',
     'radish', 'raffia', 'railroad', 'rainbow', 'rainforest', 'raspberry', 'raw silk', 'realistic', 'reclaimed wood',
     'reef', 'refined', 'reflective', 'regal', 'relief', 'reptile', 'retro', 'rhinoceros', 'ribbed', 'ribbon',
     'rice paper', 'ripple', 'river', 'rivet', 'rock', 'romantic', 'rooster', 'rope', 'rose', 'rosebud', 'rough',
     'royal', 'rug', 'rust', 'rustic', 'safari', 'sage', 'sailboat', 'saloon', 'sand', 'sandstone', 'scales',
     'scallop', 'scandinavian', 'scarecrow', 'scenic', 'sci-fi', 'scientific', 'scrapbook', 'screen', 'screenprint',
     'script', 'scroll', 'sea', 'seafoam', 'seagulls', 'seahorse', 'seals', 'seashell', 'seaweed', 'self-adhesive',
     'sequin', 'seventies', 'shabby chic', 'shamrock', 'sheen', 'shibori', 'shimmer', 'shine', 'shiny', 'ship',
     'shipwreck', 'silhouette', 'silver leaf', 'simple', 'sisal', 'sixties', 'skateboard', 'sketch', 'sketchbook',
     'skull', 'sky', 'skyline', 'skyscraper', 'slate', 'slik screen', 'sloth', 'slub yarn', 'smoke', 'snake',
     'snake skin', 'snow', 'soccer', 'solid', 'solid color', 'south', 'southwest', 'space', 'spaceship', 'spanish',
     'sparkle', 'sparkly', 'speaker', 'speckle', 'spiral', 'sponged', 'sports', 'spotted', 'square', 'squiggle',
     'squirrel', 'stained glass', 'stamp', 'star', 'starburst', 'stately', 'steel', 'stem', 'stipple', 'stitch',
     'stone', 'stork', 'strawberry', 'striated', 'stucco', 'stylized', 'subtle', 'suitcase', 'suminagashi',
     'sunflower', 'swan', 'sweet', 'swimming', 'swirl', 'sword', 'tablecloth', 'tarnished', 'tartan', 'taupe',
     'tea house', 'tea pot', 'teapot', 'tear drop', 'teddy bear', 'terrazo', 'text', 'textile', 'thorn',
     'thyme', 'tie dye', 'tiger', 'tile', 'tomatoes', 'tonal', 'topography', 'toucan', 'toy', 'train', 'transitional',
     'trash', 'travel', 'treasure map', 'tree', 'trellis', 'triangle', 'tribal', 'trompe l\'oeil', 'tufted', 'tulip',
     'turquoise', 'turtle', 'tutu', 'twill', 'umbrella', 'underwater', 'unicorn', 'universe', 'unusual',
     'upholstery', 'urban', 'variegated', 'variegated stripe', 'vase', 'vegetable', 'velour', 'velvet', 'veneer',
     'versatile', 'vertical', 'vibrant', 'victorian', 'vignette', 'village', 'vine', 'vintage', 'vinyard', 'vodka',
     'watercolor', 'wave', 'wavy', 'weathered', 'weave', 'weed', 'west', 'western', 'whitewash', 'wheat', 'whimsy',
     'wide stripes', 'wild west', 'window pane', 'wine', 'wings', 'women', 'wood', 'wood grain', 'wood panel',
     'wood plank', 'woodgrain', 'worn', 'woven', 'wreath', 'wrinkle', 'wrought iron', 'yarn', 'zebra', 'zebra print',
     'zig zag', 'zoo'
    ].each do |kw|
      Keyword.create!(name: kw)
    end
  end
end
